__title__ = 'qtcurate'
__description__ = 'Theia Python SDK for Semantic Data Extraction and Search'
__url__ = 'http://quantxt.com/'
__version__ = '1.4.7'
__author__ = 'Milojko Bjelanovic'
__author_email__ = 'mbjelanovic@quantxt.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Quantxt'
