__title__ = 'qtcurate'
__description__ = 'Theia SDK Search and Data Extraction'
__url__ = 'http://quantxt.com/'
__version__ = '1.3.2'
__author__ = 'Milojko Bjelanovic'
__author_email__ = 'mbjelanovic@quantxt.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Quantxt'
